GET http://localhost:5000/api/games

###
GET http://localhost:5000/api/games/details/street-of-rage

###CARGAR JUEGOS DE SEGA GENESIS###
POST http://localhost:5000/api/games/sync-segaMD

###CARGAR JUEGOS DE NINTENDO###
POST http://localhost:5000/api/games/sync-nes